package db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig movieDetailDaoConfig;

    private final MovieDetailDao movieDetailDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        movieDetailDaoConfig = daoConfigMap.get(MovieDetailDao.class).clone();
        movieDetailDaoConfig.initIdentityScope(type);

        movieDetailDao = new MovieDetailDao(movieDetailDaoConfig, this);

        registerDao(MovieDetail.class, movieDetailDao);
    }
    
    public void clear() {
        movieDetailDaoConfig.getIdentityScope().clear();
    }

    public MovieDetailDao getMovieDetailDao() {
        return movieDetailDao;
    }

}
